#!/bin/sh
SUSEDISTROS=$(curl http://download.opensuse.org/distribution/ 2> /dev/null| sed -re '/class..name/!d;s@.*[.][/]@@g;s@/.*@@g;/current/d')
SUSEDISTROSMICRO=$(w3m -dump http://download.opensuse.org/distribution/leap-micro |sed -re '/^[0-9]/!d;s@/ .*@@g'|sort -n -r)
SUSEDISTROSLEAP=$(w3m -dump http://download.opensuse.org/distribution/leap |sed -re '/^[0-9]/!d;s@/ .*@@g'|grep -v ^42|sort -n -r) # yes i know 42...

cat <<EOF
#!ipxe
ifopen net0
dhcp net0 ||
set menu-timeout 5000
set opensuse http://download.opensuse.org/distribution

:selection
menu Boot Selection
item --gap -- -------------            Boot Selection ------------
item --key c  advanced                 Advanced Boot Settings
item          tumbleweed               openSUSE Tumbleweed Rolling Release
item          tumbleweed_32bit         openSUSE Tumbleweed Rolling Release 32bit
item          openSUSEstable           openSUSE stable
EOF

for version in ${SUSEDISTROSLEAP}; do
case  "$version" in
	openSUSE-*)
		;;
	*-*)
		;; # ignore not released version... no repo here
	*)
cat << EOF
item          openSUSELeap${version}         openSUSE Leap ${version}
EOF
		;;
esac
done

for version in ${SUSEDISTROSMICRO}; do
case  "$version" in
	openSUSE-*)
		;;
	*-*)
		;; # ignore not released version... no repo here
	*)
cat << EOF
item          openSUSELeapMicro${version}         openSUSE Leap Micro ${version}
EOF
		;;
esac
done

#duplicated i know but...
for version in ${SUSEDISTROS}; do
case  "$version" in
	openSUSE-*)
		;;
	*-*)
		;; # ignore not released version... no repo here
	*)
cat << EOF
item          openSUSE${version}             openSUSE ${version}
# 32bit is mostly removed but lets keep it here
#item          openSUSE${version}_32bit       openSUSE ${version} 32bit
EOF
		;;
esac
done

cat << EOF
item --gap -- ------------- Boot Selection End ------------
choose --timeout \${menu-timeout} --default openSUSEstable selected || goto selection
set menu-timeout 0
goto \${selected}

:advanced
set menu-timeout 5000
menu Advanced Boot Settings
item --gap -- -------------            Advanced Boot Settings Menu ------------
item --key c  settings                 Configure network settings
item          bootdisk                 Boot from local disk
item          shell                    iPXE shell
item          tumbleweed               openSUSE Tumbleweed
item          tumbleweed_32bit         openSUSE Tumbleweed 32bit
item          back                     Back to main menu (or press ESC)
item --gap -- ------------- Advanced Boot settings End ------------
choose --timeout \${menu-timeout} --default shell selected || goto selection
set menu-timeout 0
goto \${selected}

:back
goto selection

:settings
config
goto advanced

:bootdisk
sanboot --no-describe --drive 0x80

:shell
echo type exit to return back to menu
shell
goto advanced

:realboot
kernel \${base-url}/boot/\${susearch}/loader/linux
initrd \${base-url}/boot/\${susearch}/loader/initrd
imgargs linux install=\${base-url} hostip=\${net0/ip} netmask=\${net0/netmask} gateway=\${net0/gateway} nameserver=\${dns}
boot

EOF

for version in ${SUSEDISTROS}; do
case  "$version" in
        openSUSE-*)
        	;;
	*-*)
		;; # ignore not released version... no repo here
	*)
cat << EOF
:openSUSE${version}
set susearch x86_64
set base-url \${opensuse}/${version}/repo/oss
goto realboot

EOF
	;;
esac
done


for version in ${SUSEDISTROSLEAP}; do
case  "$version" in
        openSUSE-*)
        	;;
	*-*)
		;; # ignore not released version... no repo here
	*)
cat << EOF
:openSUSELeap${version}
set susearch x86_64
set base-url \${opensuse}/leap/${version}/repo/oss
goto realboot

EOF
	;;
esac
done

for version in ${SUSEDISTROSMICRO}; do
case  "$version" in
        openSUSE-*)
        	;;
	*-*)
		;; # ignore not released version... no repo here
	*)
cat << EOF
:openSUSELeapMicro${version}
set susearch x86_64
set base-url \${opensuse}/leap-micro/${version}/product/repo/Leap-Micro-${version}-x86_64-Media/
goto realboot

EOF
	;;
esac
done

cat << EOF

:openSUSEstable
set susearch x86_64
set base-url \${opensuse}/openSUSE-stable/repo/oss
goto realboot

:tumbleweed
set susearch x86_64
set base-url \${opensuse}/../tumbleweed/repo/oss
goto realboot

:tumbleweed_32bit
set susearch i386
set base-url \${opensuse}/../ports/i586/tumbleweed/repo/oss
goto realboot
EOF
