#!/bin/sh
SUSEDISTROS=$(w3m -dump http://download.opensuse.org/distribution/ |grep '\[DIR\]'|grep -v "Parent Direc"|cut -d" " -f2|sed -e 's@/@@g'|sort -n -r)


cat <<EOF
#!ipxe
ifopen net0
dhcp net0
set menu-timeout 5000
set opensuse http://download.opensuse.org/distribution

:selection
menu Boot Selection
item --gap -- ------------- Boot Selection ------------
item          openSUSEcurrent    openSUSE current
item          openSUSEcurrent32bit    openSUSE current 32bit
item          openSUSEstable    openSUSE stable
item          openSUSEstable32bit    openSUSE stable 32bit
EOF
for version in ${SUSEDISTROS}; do
case  "$version" in
	openSUSE-*)
		;;
	*-*)
		;; # ignore not released version...
	*)
cat << EOF
item          openSUSE${version}    openSUSE ${version}
item          openSUSE${version}32bit    openSUSE ${version} 32bit
EOF
		;;
esac

done
cat << EOF
item --gap -- ------------- Boot Selection End ------------
choose --timeout \${menu-timeout} --default openSUSE-current selected || goto back
set menu-timeout 0
goto \${selected}

:realboot
kernel \${base-url}/boot/\${susearch}/loader/linux
initrd \${base-url}/boot/\${susearch}/loader/initrd
imgargs linux install=\${base-url}
boot

EOF


for version in ${SUSEDISTROS}; do
case  "$version" in
        openSUSE-*)
        	;; 
	*-*)
		;; # ignore not released version...
	*)
cat << EOF
:openSUSE${version}32bit 
set susearch i386
set base-url \${opensuse}/${version}/repo/oss
goto realboot

:openSUSE${version} 
set susearch x86_64
set base-url \${opensuse}/${version}/repo/oss
goto realboot

EOF
;;
esac
done
cat << EOF
:openSUSEcurrent
set susearch x86_64
set base-url \${opensuse}/openSUSE-current/repo/oss
goto realboot

:openSUSEcurrent32bit 
set susearch i386
set base-url \${opensuse}/openSUSE-current/repo/oss
goto realboot

:openSUSEstable
set susearch x86_64
set base-url \${opensuse}/openSUSE-stable/repo/oss
goto realboot

:openSUSEstable32bit 
set susearch i386
set base-url \${opensuse}/openSUSE-stable/repo/oss
goto realboot

EOF